title: "Settimanando"
description: "Pensieri e articoli di Nando"
baseurl: "/settimanando" # lascia vuoto se usi repo username.github.io
url: "https://ferdinando222.github.io"
theme: null   # perché stai usando un tema custom