title: "Settimanando"
description: "Pensieri e articoli di Nando"
baseurl: "" # lascia vuoto se usi repo username.github.io
url: "https://settimanando.github.io"
theme: null   # perché stai usando un tema custom